steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/gregdaybreak/spin-2-kube-app"]
    env: ["PROJECT_ROOT=github.com/gregdaybreak/spin-2-kube-app"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/tradesy-production/spin-2-kube-app:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/tradesy-production/spin-2-kube-app:$REVISION_ID"
